apiVersion: v1
kind: Service
metadata:
  name: nextfit-app
  labels:
    app: nextfit-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nextfit-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}